### ISSUE TITLE
How to use opus encoding? 

### ISSUE THREAD

**Issue by DRAMA22** [TDDung/DelphiFMX-BASS#1]
Is there a demo to encode pcm to opus and decode it back to pcm?

**Comment by DRAMA22** [comment]
Can this wrapper integrated in vcl project or just fmx?

**Comment by TDDung** [comment]
My friend, I did not test VCL but a quick review in my head tells me there should be no restriction at all as VCL can easily use Bass's DLL files since VCL is for Windows. It should very easily be tested :)

________________________________

**Comment by TDDung** [comment]
I have done that, but for the purpose of distributing the library I only included an extremely simple demo. Do you need PCM-OPUS-PCM demo?

Note: My test with opus is very extensive and multi-platform (FMX) so if you need a demo, I would have to simplify it first 🙂

________________________________
From: DRAMA22 ***@***.***>
Sent: Thursday, April 15, 2021 2:30 AM
To: TDDung/DelphiFMX-BASS ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [TDDung/DelphiFMX-BASS] How to use opus encoding? (#1)


Is there a demo to encode pcm to opus and decode it back to pcm?

**Comment by DRAMA22** [comment]
it would be great from you if you provide how to encode decode pcm audio . i was struggling to find a solution for that for a days

i am coming from kotlin and java background. in kotlin we simply load the opus library and do the encode() / decode()

for example, a brief code from my Android project using kotlin library
```
opus.Initialize
opus.EncoderInit(opval.SampleRate_16000,opval.Channels_Mono, opval.Application_VoIp)
opus.DecoderInit(opval.SampleRate_16000,opval.Channels_Mono)
opus.EncoderSetBitrate(opval.BitRate_Auto)
opus.EncoderSetComplexity(0)
AudioBytes = opus.Encode(audData, opval.FrameSize_640) ' this will return the encoded bytes
DecodedBytes =  opus.Decode(buffer, opval.FrameSize_640)
```

didn't find a similar solution for Delphi. I used this library https://github.com/lakeofsoft/vcp in Delphi to get PCM data from the microphone.

but never get success to encode its data with opus the event that holds the PCM data 

```
procedure TForm1.recDataAvailable(sender: unavclInOutPipe; data: Pointer;
  len: Cardinal);
```

**Comment by TDDung** [comment]
I know about that VCP library. It is a great one but only for Windows and is not actively developed further. Furthermore, I prefer multi-platform libraries due to modern trends 🙂

Alright, I will see what I can do for you 👌

Ah, BTW, I will post that demo onto GitHub so others can benefit from it.

________________________________

**Comment by DRAMA22** [comment]
Thank you very much that would be very helpful appreciated

**Comment by TDDung** [comment]
Here you go: https://github.com/TDDung/DelphiFMXBass-PCM_OPUS
